require("michaelyi.lazy")

require("michaelyi.conform")
require("michaelyi.lsp")
require("michaelyi.lualine")
require("michaelyi.remap")
require("michaelyi.set")
require("michaelyi.telescope")
require("michaelyi.theme")
require("michaelyi.tree")
