require("michaelyi.lazy")

require("michaelyi.conform")
require("michaelyi.copilot")
require("michaelyi.lsp")
require("michaelyi.remap")
require("michaelyi.set")
require("michaelyi.telescope")
require("michaelyi.theme")
require("michaelyi.treesitter")
